on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure ffmpeg is available
        run: |
          if ! command -v ffmpeg >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y ffmpeg
          fi
          ffmpeg -version

      - name: Make script executable
        run: chmod +x scripts/render.sh

      - name: Run render script
        run: |
          # optionally set WATERMARK env if you want
          # WATERMARK="@your_handle" bash scripts/render.sh
          bash scripts/render.sh

      - name: Upload generated videos and logs
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/**
          retention-days: 7
