name: Render YouTube Short
on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Make script executable
        run: chmod +x scripts/render.sh

      - name: Run render script (debug enabled)
        run: |
          echo "Running render script on branch: $GITHUB_REF"
          ls -la
          bash -x scripts/render.sh

      - name: List out directory before upload
        run: |
          echo "Out directory contents:"
          ls -la out || true
          echo "ffmpeg log (if any):"
          sed -n '1,200p' out/ffmpeg.log || true

      - name: Upload out artifact
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/**
          retention-days: 7
