jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run render script
        run: bash scripts/render.sh
      - name: Upload generated videos and logs
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/**
          retention-days: 14